### ISSUE TITLE
Fatal: undefined method `include?' for nil:NilClass

### ISSUE THREAD

**Issue by LinuxMercedes** [taskjuggler/TaskJuggler#149]
When running tj3d or tj3webd, I get the following error:

```
[31mFatal: undefined method `include?' for nil:NilClass
/usr/local/home/XXX/.rvm/gems/ruby-2.1.0/gems/taskjuggler-3.5.0/lib/taskjuggler/RuntimeConfig.rb:60:in `block in configure'
/usr/local/home/XXX/.rvm/gems/ruby-2.1.0/gems/taskjuggler-3.5.0/lib/taskjuggler/RuntimeConfig.rb:57:in `each'
/usr/local/home/XXX/.rvm/gems/ruby-2.1.0/gems/taskjuggler-3.5.0/lib/taskjuggler/RuntimeConfig.rb:57:in `configure'
/usr/local/home/XXX/.rvm/gems/ruby-2.1.0/gems/taskjuggler-3.5.0/lib/taskjuggler/apps/Tj3Daemon.rb:81:in `appMain'
/usr/local/home/XXX/.rvm/gems/ruby-2.1.0/gems/taskjuggler-3.5.0/lib/taskjuggler/Tj3AppBase.rb:146:in `main'
/usr/local/home/XXX/.rvm/gems/ruby-2.1.0/gems/taskjuggler-3.5.0/lib/tj3d.rb:16:in `<top (required)>'
/usr/local/home/XXX/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/home/XXX/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/home/XXX/.rvm/gems/ruby-2.1.0/gems/taskjuggler-3.5.0/bin/tj3d:4:in `<top (required)>'
/usr/local/home/XXX/.rvm/gems/ruby-2.1.0/bin/tj3d:23:in `load'
/usr/local/home/XXX/.rvm/gems/ruby-2.1.0/bin/tj3d:23:in `<main>'
/usr/local/home/XXX/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
/usr/local/home/XXX/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'

*******************************************************************************
You have triggered a bug in TaskJuggler version 3.5.0!
Please see the user manual on how to get this bug fixed!
http://www.taskjuggler.org/tj3/manual/Reporting_Bugs.html#Reporting_Bugs_and_Feature_Requests
*******************************************************************************
[0m
/usr/local/home/XXX/.rvm/gems/ruby-2.1.0/gems/taskjuggler-3.5.0/lib/taskjuggler/MessageHandler.rb:301:in `addMessage': RuntimeError (RuntimeError)
    from /usr/local/home/XXX/.rvm/gems/ruby-2.1.0/gems/taskjuggler-3.5.0/lib/taskjuggler/MessageHandler.rb:190:in `fatal'
    from /usr/local/home/XXX/.rvm/gems/ruby-2.1.0/gems/taskjuggler-3.5.0/lib/taskjuggler/MessageHandler.rb:312:in `fatal'
    from /usr/local/home/XXX/.rvm/gems/ruby-2.1.0/gems/taskjuggler-3.5.0/lib/taskjuggler/Tj3AppBase.rb:161:in `rescue in main'
    from /usr/local/home/XXX/.rvm/gems/ruby-2.1.0/gems/taskjuggler-3.5.0/lib/taskjuggler/Tj3AppBase.rb:127:in `main'
    from /usr/local/home/XXX/.rvm/gems/ruby-2.1.0/gems/taskjuggler-3.5.0/lib/tj3d.rb:16:in `<top (required)>'
    from /usr/local/home/XXX/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/home/XXX/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/home/XXX/.rvm/gems/ruby-2.1.0/gems/taskjuggler-3.5.0/bin/tj3d:4:in `<top (required)>'
    from /usr/local/home/XXX/.rvm/gems/ruby-2.1.0/bin/tj3d:23:in `load'
    from /usr/local/home/XXX/.rvm/gems/ruby-2.1.0/bin/tj3d:23:in `<main>'
    from /usr/local/home/XXX/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
    from /usr/local/home/XXX/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
```

```
$ruby -v
ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-linux]
```

I can produce this error with the tutorial.tjp file. I get this on both my Arch Linux box and an Ubuntu 12.04 machine.

**Comment by scrapper** [comment]
Can you send me your taskjugglerrc file that you are using for tj3d?

**Comment by LinuxMercedes** [comment]
Here's what I've got: 

```
project a "A" 2015-01-28 +4m {
  timezone "America/Chicago"
  timeformat "%Y-%m-%d"
  numberformat "-" "" "," "." 1
}

task t "T" {
  task tt "TT" {
    duration 3d
  }
}

macro TaskTip [
  tooltip istask() -8<-
    '''Start: ''' <-query attribute='start'->
    '''End: ''' <-query attribute='end'->
    ----
    '''Resources:'''

    <-query attribute='resources'->
    ----
    '''Precursors: '''

    <-query attribute='precursors'->
    ----
    '''Followers: '''

    <-query attribute='followers'->
    ->8-
]

textreport frame "" {
  textreport index "Overview" {
    formats html
    center '<[report id="overview"]>'
  }
}

taskreport overview "" {
  columns bsi { title 'WBS' }, name, start, end, chart { ${TaskTip} }
}
```

And my `.taskjugglerrc` for fun:

```
_global:
authkey: hunter2
```


The command I'm running is `tj3d gantt.tjp`.
