### ISSUE TITLE
Inactive root scenario causes exceptions

### ISSUE THREAD

**Issue by Xowap** [taskjuggler/TaskJuggler#160]
I try to have an inactive root scenario, because I want to simulate different resource allocation plans which have nothing in common. The only issue is that it produces an exception:

```
project test "Test" 2015-01-01 +1m {
  timezone "Europe/Paris"
  now 2015-01-01-09:00

  scenario plan "Plan" {
    active no
    scenario subplan1 "Sub Plan 1"
  }
}

resource testr "Test Resource"

task testt "Test Task" {
  effort 1w
  subplan1:allocate testr
}

taskreport tasks "tasks" {
  formats html
}
```

Output:

```
% tj3 test.tjp
TaskJuggler v3.5.0 - A Project Management Software

Copyright (c) 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013
              by Chris Schlaeger <chris@linux.com>

This program is free software; you can redistribute it and/or modify it under
the terms of version 2 of the GNU General Public License as published by the
Free Software Foundation.

Reading file test.tjp                                        [      Done      ]
Fatal: Overwriting a previously provided value for attribute tree
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/PropertyTreeNode.rb:444:in `set'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/PropertyList.rb:265:in `block in indexTree'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/PropertyList.rb:253:in `each'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/PropertyList.rb:253:in `indexTree'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/PropertyList.rb:167:in `sort!'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/reports/TaskListRE.rb:46:in `generateIntermediateFormat'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/reports/Report.rb:148:in `generateIntermediateFormat'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/reports/Report.rb:73:in `generate'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/Project.rb:727:in `block in generateReports'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/PropertySet.rb:297:in `block in each'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/PropertySet.rb:296:in `each'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/PropertySet.rb:296:in `each'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/Project.rb:720:in `generateReports'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/TaskJuggler.rb:158:in `generateReports'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/apps/Tj3.rb:214:in `appMain'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/Tj3AppBase.rb:146:in `main'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/tj3.rb:16:in `<top (required)>'
/home/remy/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/remy/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/bin/tj3:4:in `<top (required)>'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/bin/tj3:23:in `load'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/bin/tj3:23:in `<main>'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/bin/ruby_executable_hooks:15:in `eval'
/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/bin/ruby_executable_hooks:15:in `<main>'

*******************************************************************************
You have triggered a bug in TaskJuggler version 3.5.0!
Please see the user manual on how to get this bug fixed!
http://www.taskjuggler.org/tj3/manual/Reporting_Bugs.html#Reporting_Bugs_and_Feature_Requests
*******************************************************************************

/home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/MessageHandler.rb:301:in `addMessage': RuntimeError (RuntimeError)
        from /home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/MessageHandler.rb:190:in `fatal'
        from /home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/MessageHandler.rb:312:in `fatal'
        from /home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/Tj3AppBase.rb:161:in `rescue in main'
        from /home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/taskjuggler/Tj3AppBase.rb:127:in `main'
        from /home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/lib/tj3.rb:16:in `<top (required)>'
        from /home/remy/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/remy/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/gems/taskjuggler-3.5.0/bin/tj3:4:in `<top (required)>'
        from /home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/bin/tj3:23:in `load'
        from /home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/bin/tj3:23:in `<main>'
        from /home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/bin/ruby_executable_hooks:15:in `eval'
        from /home/remy/.rvm/gems/ruby-1.9.3-p551@tj3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by scrapper** [comment]
Thanks for reporting this bug! It's now fixed in the git repository and will be included in the next release.

**Comment by Xowap** [comment]
:ok_hand:
