### ISSUE TITLE
Importing tutorial example file crashes tj3d

### ISSUE THREAD

**Issue by ant11** [taskjuggler/TaskJuggler#161]
I have an empty tj3d running. Then I add the tutorial.tjp (http://www.taskjuggler.org/tj3/examples/Tutorial/tutorial.tjp ) via tj3client: 

```
$ tj3client -c projects/tutorial1/.taskjugglerrc add projects/tutorial1/tutorial1.tjp
TaskJuggler v3.5.0 - A Project Management Software

Copyright (c) 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013
          by Chris Schlaeger <chris@linux.com>

This program is free software; you can redistribute it and/or modify it under
the terms of version 2 of the GNU General Public License as published by the
Free Software Foundation.

Warning: Projects(s) projects/tutorial1/tutorial1.tjp could not be added
```

And the output of 

```
$ tj3client -c .taskjugglerrc status
```

looks like this:

```
TaskJuggler v3.5.0 - A Project Management Software

Copyright (c) 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013
          by Chris Schlaeger <chris@linux.com>

This program is free software; you can redistribute it and/or modify it under
the terms of version 2 of the GNU General Public License as published by the
Free Software Foundation.

  No. | Project ID                | Status         | M | Loaded since
  ----+---------------------------+----------------+---+--------------------
    1 | projects/tutorial/tutorial.tjp | loading        |   |
```

The logfile of this says this:

```
2014-12-28 21:22:00 warning tj3d[15731]: Loading of project failed: connection closed
2014-12-28 21:25:17 fatal tj3d[15731]: undefined method `state' for nil:NilClass
/usr/lib64/ruby/gems/2.0.0/gems/taskjuggler-3.5.0/lib/taskjuggler/daemon/ProjectBroker.rb:270:in     `block in removeProject'
/usr/lib64/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/usr/lib64/ruby/gems/2.0.0/gems/taskjuggler-3.5.0/lib/taskjuggler/daemon/ProjectBroker.rb:262:in `removeProject'
/usr/lib64/ruby/gems/2.0.0/gems/taskjuggler-3.5.0/lib/taskjuggler/daemon/ProjectBroker.rb:541:in `block in command'
/usr/lib64/ruby/gems/2.0.0/gems/taskjuggler-3.5.0/lib/taskjuggler/daemon/ProjectBroker.rb:506:in `trap'
/usr/lib64/ruby/gems/2.0.0/gems/taskjuggler-3.5.0/lib/taskjuggler/daemon/ProjectBroker.rb:530:in `command'
/usr/lib64/ruby/2.0.0/drb/drb.rb:1588:in `perform_without_block'
/usr/lib64/ruby/2.0.0/drb/drb.rb:1548:in `perform'
/usr/lib64/ruby/2.0.0/drb/drb.rb:1626:in `block (2 levels) in main_loop'
/usr/lib64/ruby/2.0.0/drb/drb.rb:1622:in `loop'
/usr/lib64/ruby/2.0.0/drb/drb.rb:1622:in `block in main_loop'

*******************************************************************************
You have triggered a bug in TaskJuggler version 3.5.0!
Please see the user manual on how to get this bug fixed!
*******************************************************************************

2014-12-28 21:30:48 warning tj3d[25750]: Loading of project failed: connection closed
2014-12-28 21:45:48 error tj3d[26652]: Reached timeout for state loading. Terminating.
2014-12-28 21:45:48 fatal tj3d[26652]: ProjectServer housekeeping error: druby://127.0.0.1:39564 - #<Errno::ECONNREFUSED: Connection refused - connect(2)>
```

**Comment by jostber** [comment]
Do you have ruby with yaml installed?

https://github.com/taskjuggler/TaskJuggler/issues/77

**Comment by cgudrian** [comment]
Remove the timezone definition from the project header and everything should work again. TaskJuggler tries to set the TZ environment variable which is prohibited by Ruby's security mechanisms. Under the hood a SecurityError is raised at TjTime.rb:79 (cf. #168).

**Comment by deepfire** [comment]
A new release is needed to fix this.. time zone setting is fairly important.

**Comment by jostber** [comment]
Is there a way to go around this issue?

**Comment by lbriais** [comment]
One year later I have exactly the same problem...
Can't add any `.tjp` file. Not only `tutorial.tjp`, but also the `template.tjp` file, which is supposed to be empty...

Is taskjuggler an abandonware ?

**Comment by jostber** [comment]
On 03.03.17,00:36, L.Briais wrote:
>One year later I have exactly the same problem...
>Can't add any `.tjp` file. Not only `tutorial.tjp`, but also the `template.tjp` file, which is supposed to be empty...
>
>Is taskjuggler an abandonware ?
>

Can you comment out your timezone setting in these files and check if it
works then?


Jostein

**Comment by lbriais** [comment]
Thank you Jostein, it actually works after commenting out TZ settings.
But the question is then __why isn't that the default in all example files__? It gives a very bad first impression of the software quality, whereas it looks like there is a lot of work in that software...

**Comment by gbiscuolo** [comment]
Hello @cgudrian, I'm packaging TaskJuggler 3.7.1 for Guix (https://debbugs.gnu.org/cgi/bugreport.cgi?bug=49042)

> Remove the timezone definition from the project header and everything
> should work again. TaskJuggler tries to set the TZ environment
> variable which is prohibited by Ruby's security mechanisms. Under the
> hood a SecurityError is raised at TjTime.rb:79 (cf. #168).

I'm getting the same error as reported in #168 and I'm considering applying the patch proposed by @PiQuer (https://github.com/taskjuggler/TaskJuggler/issues/168#issuecomment-104076790)

I'm pretty new to Ruby, please can you point me to a reference documentation that explains setting TZ env is prohibited?

Thank you for your support! Giovanni.

**Comment by cgudrian** [comment]
Hi, Giovanni!

> I'm pretty new to Ruby, please can you point me to a reference documentation that explains setting TZ env is prohibited?

It's not that setting the TZ environment variable is prohibited per se. A ruby script can raise its security level to prevent certain insecure operations. Obviously the code in question is executed with such security restrictions in place.

I've never myself experienced that particular problem with TaskJuggler (and am not an active user anymore for years). I've merely pointed out the connection between these issues.

I wonder if this error still exists given the time that has passed since then.

Regards,

Christian
