### ISSUE TITLE
method_missing bug

### ISSUE THREAD

**Issue by mirkov** [taskjuggler/TaskJuggler#189]
I have triggered a bug in 3.6.0. (Windows 7, Ruby22-x64).  I use Emacs' Org mode to generate the tjp file.

I get a very long trace (a few thousand lines) that repeats the following messages:
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/TaskSce
nario.rb:2410:in `block in calcPathCriticalnessEndSuccs'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/TaskSce
nario.rb:2409:in `each'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/TaskSce
nario.rb:2409:in `calcPathCriticalnessEndSuccs'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/TaskSce
nario.rb:896:in `calcPathCriticalness'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Propert
yTreeNode.rb:710:in `method_missing'

These messges keep repeating until at the end I see:

C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Project
.rb:1117:in `prepareScenario'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Project
.rb:648:in `block in schedule'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Propert
ySet.rb:301:in `block in each'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Propert
ySet.rb:300:in `each'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Propert
ySet.rb:300:in `each'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Project
.rb:637:in `schedule'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/TaskJug
gler.rb:130:in `schedule'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/apps/Tj
3.rb:189:in `appMain'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Tj3AppB
ase.rb:146:in `main'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/tj3.rb:16:in `<top
(required)>'
C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'

C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'

C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/bin/tj3:4:in `<top (req
uired)>'
C:/Ruby22-x64/bin/tj3:23:in `load'
C:/Ruby22-x64/bin/tj3:23:in `<main>'

I have seen this bug already once in my file, but it somehow went away.  I will try to isolate the cause of the bug.  (Unfortunately I cannot share the project file.)  If I get a feel for it, I will try to generate a minimal case.

Any other suggestions on what could be causing it.

Mirko

**Comment by mirkov** [comment]
A follow-up:

I was able to eliminate the crash.  I first removed all start/end dates.
Then tj3 pointed out a circular dependency. After fixing that, I started adding the dates, and the schedule compiled.

Mirko

**Comment by scrapper** [comment]
On 2016-05-12 22:24, mirkov wrote:
> I have triggered a bug in 3.6.0. (Windows 7, Ruby22-x64). I use Emacs'
> Org mode to generate the tjp file.
> 
> I get a very long trace (a few thousand lines) that repeats the
> following messages:
> C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/TaskSce
> nario.rb:2410:in block in calcPathCriticalnessEndSuccs'
> C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/TaskSce
> nario.rb:2409:ineach'
> C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/TaskSce
> nario.rb:2409:in calcPathCriticalnessEndSuccs'
> C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/TaskSce
> nario.rb:896:incalcPathCriticalness'
> C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Propert
> yTreeNode.rb:710:in `method_missing'
> 
> These messges keep repeating until at the end I see:
> 
> C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Project

I think you left the out the most important line that contains the 
actual error message. These are just location infos.

Chris
