### ISSUE TITLE
undefined method `[]' for nil:NilClass MacOS Ruby 2.1.9

### ISSUE THREAD

**Issue by AKielhorn** [taskjuggler/TaskJuggler#190]
Hello,

I installed ruby via Macports on Mac OS X 10.10:
```
ruby --version
ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-darwin14]
```
I installed taskjuggler via gem.

When I run tj3 on a project, I get the html files as designed.

When I run tj3d or tj3webd I get:

```
TJ axel$ tj3d
TaskJuggler v3.6.0 - A Project Management Software

Copyright (c) 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016
              by Chris Schlaeger <cs@taskjuggler.org>

This program is free software; you can redistribute it and/or modify it under
the terms of version 2 of the GNU General Public License as published by the
Free Software Foundation.

Fatal: undefined method `[]' for nil:NilClass
/opt/local/lib/ruby2.1/gems/2.1.0/gems/taskjuggler-3.6.0/lib/taskjuggler/RuntimeConfig.rb:50:in `block in configure'
/opt/local/lib/ruby2.1/gems/2.1.0/gems/taskjuggler-3.6.0/lib/taskjuggler/RuntimeConfig.rb:49:in `each'
/opt/local/lib/ruby2.1/gems/2.1.0/gems/taskjuggler-3.6.0/lib/taskjuggler/RuntimeConfig.rb:49:in `configure'
/opt/local/lib/ruby2.1/gems/2.1.0/gems/taskjuggler-3.6.0/lib/taskjuggler/apps/Tj3Daemon.rb:85:in `appMain'
/opt/local/lib/ruby2.1/gems/2.1.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Tj3AppBase.rb:146:in `main'
/opt/local/lib/ruby2.1/gems/2.1.0/gems/taskjuggler-3.6.0/lib/tj3d.rb:16:in `<top (required)>'
/opt/local/lib/ruby2.1/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/local/lib/ruby2.1/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/local/lib/ruby2.1/gems/2.1.0/gems/taskjuggler-3.6.0/bin/tj3d:4:in `<top (required)>'
/opt/local/bin/tj3d:23:in `load'
/opt/local/bin/tj3d:23:in `<main>'

*******************************************************************************
You have triggered a bug in TaskJuggler version 3.6.0!
Please see the user manual on how to get this bug fixed!
http://www.taskjuggler.org/tj3/manual/Reporting_Bugs.html#Reporting_Bugs_and_Feature_Requests
*******************************************************************************

/opt/local/lib/ruby2.1/gems/2.1.0/gems/taskjuggler-3.6.0/lib/taskjuggler/MessageHandler.rb:301:in `addMessage': RuntimeError (RuntimeError)
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/taskjuggler-3.6.0/lib/taskjuggler/MessageHandler.rb:190:in `fatal'
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/taskjuggler-3.6.0/lib/taskjuggler/MessageHandler.rb:312:in `fatal'
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Tj3AppBase.rb:161:in `rescue in main'
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Tj3AppBase.rb:127:in `main'
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/taskjuggler-3.6.0/lib/tj3d.rb:16:in `<top (required)>'
	from /opt/local/lib/ruby2.1/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/local/lib/ruby2.1/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/local/lib/ruby2.1/gems/2.1.0/gems/taskjuggler-3.6.0/bin/tj3d:4:in `<top (required)>'
	from /opt/local/bin/tj3d:23:in `load'
	from /opt/local/bin/tj3d:23:in `<main>'
```

I installed the gem as administrator but run tj3d as user.
I do not have a .traskjugglerrc

The task juggler Project was exported from the example used in org-modes Taskjuggler exporter.
But even with no tjp file I get the same error.

I got the same results with ruby 2.2, that's why I went back to 2.1.

Any ideas?

Axel
[ox-taskjuggler.tjp.txt](https://github.com/taskjuggler/TaskJuggler/files/314331/ox-taskjuggler.tjp.txt)

**Comment by barik** [comment]
I am receiving a similar error when using `Windows 10` and `ruby 2.3.0p0`.

```
C:\planning>tj3webd
TaskJuggler v3.6.0 - A Project Management Software

Copyright (c) 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016
              by Chris Schlaeger <cs@taskjuggler.org>

This program is free software; you can redistribute it and/or modify it under
the terms of version 2 of the GNU General Public License as published by the
Free Software Foundation.

Fatal: undefined method `[]' for nil:NilClass
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taskjuggler-3.6.0/lib/taskjuggler/RuntimeConfig.rb:50:in `block in configure'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taskjuggler-3.6.0/lib/taskjuggler/RuntimeConfig.rb:49:in `each'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taskjuggler-3.6.0/lib/taskjuggler/RuntimeConfig.rb:49:in `configure'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taskjuggler-3.6.0/lib/taskjuggler/apps/Tj3WebD.rb:81:in `appMain'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Tj3AppBase.rb:146:in `main'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taskjuggler-3.6.0/lib/tj3webd.rb:16:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taskjuggler-3.6.0/bin/tj3webd:4:in `<top (required)>'
C:/Ruby23-x64/bin/tj3webd:23:in `load'
C:/Ruby23-x64/bin/tj3webd:23:in `<main>'

*******************************************************************************
You have triggered a bug in TaskJuggler version 3.6.0!
Please see the user manual on how to get this bug fixed!
http://www.taskjuggler.org/tj3/manual/Reporting_Bugs.html#Reporting_Bugs_and_Feature_Requests
*******************************************************************************

C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taskjuggler-3.6.0/lib/taskjuggler/MessageHandler.rb:301:in `addMessage': RuntimeError (RuntimeError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taskjuggler-3.6.0/lib/taskjuggler/MessageHandler.rb:190:in `fatal'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taskjuggler-3.6.0/lib/taskjuggler/MessageHandler.rb:312:in `fatal'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Tj3AppBase.rb:161:in `rescue in main'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Tj3AppBase.rb:127:in `main'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taskjuggler-3.6.0/lib/tj3webd.rb:16:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/taskjuggler-3.6.0/bin/tj3webd:4:in `<top (required)>'
        from C:/Ruby23-x64/bin/tj3webd:23:in `load'
        from C:/Ruby23-x64/bin/tj3webd:23:in `<main>'
```

**Comment by anebuch** [comment]
I had the same error on open-suse. Creating a file named taskjuggler.rc in /etc/ with the following content helped.

 `vim /etc/taskjuggler.rc
_global:
   authKey: your-passphrase`

**Comment by AlexanderAA** [comment]
@anebuch's  comment helped to solve the issue for me

**Comment by deepfire** [comment]
Same error while packaging for NixOS.

**Comment by jostber** [comment]
I believe this issue can be closed.

**Comment by AlexisWilke** [comment]
Pretty much the same thing under Ubuntu:

    Apr 10 12:23:08 monster tj3d[24140]: Fatal: undefined method `[]' for false:FalseClass
    Apr 10 12:23:08 monster tj3d[24140]: /usr/lib/ruby/vendor_ruby/taskjuggler/RuntimeConfig.rb:50:in `block in configure'
    Apr 10 12:23:08 monster tj3d[24140]: /usr/lib/ruby/vendor_ruby/taskjuggler/RuntimeConfig.rb:49:in `each'
    Apr 10 12:23:08 monster tj3d[24140]: /usr/lib/ruby/vendor_ruby/taskjuggler/RuntimeConfig.rb:49:in `configure'
    Apr 10 12:23:08 monster tj3d[24140]: /usr/lib/ruby/vendor_ruby/taskjuggler/apps/Tj3Daemon.rb:87:in `appMain'
    Apr 10 12:23:08 monster tj3d[24140]: /usr/lib/ruby/vendor_ruby/taskjuggler/Tj3AppBase.rb:160:in `main'
    Apr 10 12:23:08 monster tj3d[24140]: /usr/lib/ruby/vendor_ruby/tj3d.rb:16:in `<top (required)>'
    Apr 10 12:23:08 monster tj3d[24140]: /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
    Apr 10 12:23:08 monster tj3d[24140]: /usr/bin/tj3d:4:in `<main>'

when I try to run the daemon.

**Comment by jostber** [comment]
Make a taskjuggler.rc file and place it in ~

vim ~/taskjuggler.rc

_global:
  authKey: <passphrase>
  webServerPort: 8080
_log:
    logLevel: 3
    outputLevel: 3

**Comment by AlexisWilke** [comment]
Ah, that worked. So the bug is to tell people that the configuration file is required instead of saying "what the heck is that []"?

Also, the spaces are super important in the config file otherwise it won't work:

    _global:
      authKey:
      webServerPort: 8080
    _log:
      logLevel: 3
      outputLevel: 3

If you use the `--config` option, you can place that file anywhere you want. It doesn't need to be `~/taskjuggler.rc`. For example, here is an entry to have the server available to yourself as a systemd service (see the `--config` option on the command line):

    [Unit]
    Description=TaskJuggler Service
    
    [Service]
    ExecStart=/usr/bin/tj3d --dont-daemonize --logfile /home/alexis/logs/tj3.log --webserver --webserver-port 8475 --silent --no-color --config /home/alexis/.config/tj3/tj3.conf
    
    [Install]
    WantedBy=default.target

Save that file under `~/.config/systemd/user/tj3.service`

After adding a new file, reload with:

    systemctl --user daemon-reload

To enable the service use:

    systemctl --user enable tj3

To start the service use:

    systemctl --user start tj3

**IMPORTANT NOTE:** The `systemctl` is used **without** the usual `sudo` when you create a user service. (Otherwise it would see `root` as the user. I know. Duh.)

**Comment by scrapper** [comment]
Which taskjuggler version was that? This issue should be fixed in 3.7.1.

**Comment by AlexisWilke** [comment]
Ah. I installed the version coming with Ubuntu 18.04 which is 3.6.0

    /var/cache/apt/archives/tj3_3.6.0-4_all.deb

I probably should use the [Ruby Gem](https://rubygems.org/gems/taskjuggler) version instead.
