### ISSUE TITLE
tj3webd command fails - triggers a bug message

### ISSUE THREAD

**Issue by srustamo** [taskjuggler/TaskJuggler#216]
OSX 10.9.5

Command and its output below:

```
 ❯ tj3webd
  2 /Users/a3/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/taskjuggler-3.6.0/lib/taskjuggler/MessageHandler.rb:233: warning: constant ::Fixnum is deprecated
  3 TaskJuggler v3.6.0 - A Project Management Software
  4
  5 Copyright (c) 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016
  6               by Chris Schlaeger <cs@taskjuggler.org>
  7
  8 This program is free software; you can redistribute it and/or modify it under
  9 the terms of version 2 of the GNU General Public License as published by the
 10 Free Software Foundation.
 11
 12 Fatal: undefined method `[]' for nil:NilClass
 13 /Users/a3/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/taskjuggler-3.6.0/lib/taskjuggler/RuntimeConfig.rb:50:in `block in configure'
 14 /Users/a3/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/taskjuggler-3.6.0/lib/taskjuggler/RuntimeConfig.rb:49:in `each'
 15 /Users/a3/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/taskjuggler-3.6.0/lib/taskjuggler/RuntimeConfig.rb:49:in `configure'
 16 /Users/a3/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/taskjuggler-3.6.0/lib/taskjuggler/apps/Tj3WebD.rb:81:in `appMain'
 17 /Users/a3/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Tj3AppBase.rb:146:in `main'
 18 /Users/a3/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/taskjuggler-3.6.0/lib/tj3webd.rb:16:in `<top (required)>'
 19 /Users/a3/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 20 /Users/a3/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 21 /Users/a3/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/taskjuggler-3.6.0/bin/tj3webd:4:in `<top (required)>'
 22 /Users/a3/.rbenv/versions/2.4.2/bin/tj3webd:23:in `load'
 23 /Users/a3/.rbenv/versions/2.4.2/bin/tj3webd:23:in `<main>'
 24
 25 *******************************************************************************
 26 You have triggered a bug in TaskJuggler version 3.6.0!
 27 Please see the user manual on how to get this bug fixed!
 28 http://www.taskjuggler.org/tj3/manual/Reporting_Bugs.html#Reporting_Bugs_and_Feature_Requests
 29 *******************************************************************************
 30
 31 /Users/a3/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/taskjuggler-3.6.0/lib/taskjuggler/MessageHandler.rb:301:in `addMessage': RuntimeError (RuntimeError)
 32         from /Users/a3/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/taskjuggler-3.6.0/lib/taskjuggler/MessageHandler.rb:190:in `fatal'
 33         from /Users/a3/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/taskjuggler-3.6.0/lib/taskjuggler/MessageHandler.rb:312:in `fatal'
 34         from /Users/a3/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Tj3AppBase.rb:161:in `rescue in main'
 35         from /Users/a3/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/taskjuggler-3.6.0/lib/taskjuggler/Tj3AppBase.rb:127:in `main'
 36         from /Users/a3/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/taskjuggler-3.6.0/lib/tj3webd.rb:16:in `<top (required)>'
 37         from /Users/a3/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 38         from /Users/a3/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 39         from /Users/a3/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/taskjuggler-3.6.0/bin/tj3webd:4:in `<top (required)>'
 40         from /Users/a3/.rbenv/versions/2.4.2/bin/tj3webd:23:in `load'
 41         from /Users/a3/.rbenv/versions/2.4.2/bin/tj3webd:23:in `<main>'

```

**Comment by srustamo** [comment]
Same as https://github.com/taskjuggler/TaskJuggler/issues/190
