### ISSUE TITLE
accountprefix crash

### ISSUE THREAD

**Issue by platise** [taskjuggler/TaskJuggler#218]
For some .tjp having declared in TaskJuggler v3.6.0:
```
account material "Material Costs"
include "account_costs.tji" { accountprefix material }
```
and account_costs.tji with:
```
account purchase "Purchase" {
    credits 2017-05-16 "Test1" 224,
            2017-05-03 "Test2" 8,
            2017-05-16 "Test3" 90,
            2017-06-30 "Test4" 192
}
```
crashes:
```
Fatal: undefined method `accout' for #<TaskJuggler::Project:0x00556ea3781790>
Did you mean?  account
               accounts
/usr/local/share/gems/gems/taskjuggler-3.6.0/lib/taskjuggler/TjpSyntaxRules.rb:79:in `block in rule_accountHeader'
/usr/local/share/gems/gems/taskjuggler-3.6.0/lib/taskjuggler/TextParser.rb:394:in `finishPattern'
/usr/local/share/gems/gems/taskjuggler-3.6.0/lib/taskjuggler/TextParser.rb:346:in `block in parseFSM'
/usr/local/share/gems/gems/taskjuggler-3.6.0/lib/taskjuggler/TextParser.rb:272:in `loop'
/usr/local/share/gems/gems/taskjuggler-3.6.0/lib/taskjuggler/TextParser.rb:272:in `parseFSM'
/usr/local/share/gems/gems/taskjuggler-3.6.0/lib/taskjuggler/TextParser.rb:201:in `parse'
/usr/local/share/gems/gems/taskjuggler-3.6.0/lib/taskjuggler/TaskJuggler.rb:67:in `block in parse'
/usr/local/share/gems/gems/taskjuggler-3.6.0/lib/taskjuggler/TaskJuggler.rb:55:in `each'
/usr/local/share/gems/gems/taskjuggler-3.6.0/lib/taskjuggler/TaskJuggler.rb:55:in `parse'
/usr/local/share/gems/gems/taskjuggler-3.6.0/lib/taskjuggler/apps/Tj3.rb:185:in `appMain'
/usr/local/share/gems/gems/taskjuggler-3.6.0/lib/taskjuggler/Tj3AppBase.rb:146:in `main'
/usr/local/share/gems/gems/taskjuggler-3.6.0/lib/tj3.rb:16:in `<top (required)>'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:68:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:68:in `require'
/usr/local/share/gems/gems/taskjuggler-3.6.0/bin/tj3:4:in `<top (required)>'
/usr/local/bin/tj3:23:in `load'
/usr/local/bin/tj3:23:in `<main>'

*******************************************************************************
You have triggered a bug in TaskJuggler version 3.6.0!
Please see the user manual on how to get this bug fixed!
http://www.taskjuggler.org/tj3/manual/Reporting_Bugs.html#Reporting_Bugs_and_Feature_Requests
*******************************************************************************

/usr/local/share/gems/gems/taskjuggler-3.6.0/lib/taskjuggler/MessageHandler.rb:301:in `addMessage': RuntimeError (RuntimeError)
	from /usr/local/share/gems/gems/taskjuggler-3.6.0/lib/taskjuggler/MessageHandler.rb:190:in `fatal'
	from /usr/local/share/gems/gems/taskjuggler-3.6.0/lib/taskjuggler/MessageHandler.rb:312:in `fatal'
	from /usr/local/share/gems/gems/taskjuggler-3.6.0/lib/taskjuggler/Tj3AppBase.rb:161:in `rescue in main'
	from /usr/local/share/gems/gems/taskjuggler-3.6.0/lib/taskjuggler/Tj3AppBase.rb:127:in `main'
	from /usr/local/share/gems/gems/taskjuggler-3.6.0/lib/tj3.rb:16:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/share/gems/gems/taskjuggler-3.6.0/bin/tj3:4:in `<top (required)>'
	from /usr/local/bin/tj3:23:in `load'
	from /usr/local/bin/tj3:23:in `<main>'
```

**Comment by platise** [comment]
This one was easy, here is the fix:
```
diff --git a/lib/taskjuggler/TjpSyntaxRules.rb b/lib/taskjuggler/TjpSyntaxRules.rb
index e7c7510..bb4d028 100644
--- a/lib/taskjuggler/TjpSyntaxRules.rb
+++ b/lib/taskjuggler/TjpSyntaxRules.rb
@@ -76,7 +76,7 @@ EOT
   def rule_accountHeader
     pattern(%w( _account !optionalID $STRING ), lambda {
       if @property.nil? && !@accountprefix.empty?
-        @property = @project.accout(@accountprefix)
+        @property = @project.account(@accountprefix)
       end
       if @val[1] && @project.account(@val[1])
         error('account_exists', "Account #{@val[1]} has already been defined.",
```

**Comment by scrapper** [comment]
Obviously correct. Thanks for finding and fixing it! I've committed your patch.
